version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000 # expose port 8000 to the outside world to be picked up with nginx. If not using nginx, you can use ports: - 8000:8000 
    env_file:
      - ./.env.prod

  redis:
    image: redis:7.0.11-alpine
    restart: always
    
  celery_worker:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: /usr/src/app/celery_entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: /usr/src/app/celery_beat_entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
