version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
  
  redis:
    image: redis:7.0.11-alpine
    restart: always
    
  celery_worker:
    build:  ./app
    command: /usr/src/app/celery_entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery_beat:
    build: ./app
    command: /usr/src/app/celery_beat_entrypoint.sh
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis
